name: weliveapp
description: The WE Live App project by Jay Jakkrit.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.3
  english_words: ^4.0.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.2
  flutter_facebook_auth_platform_interface: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.6.17+3
  github: ^9.19.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  provider: ^6.0.5
  url_launcher: ^6.1.14

flutter_icons:
  web:
    generate: true
    image_path: "assets/images/weliveapp-icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
