name: weliveapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.17+3
  github: ^9.19.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
